name: Node CI

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Uses PNPM
      uses: pnpm/action-setup@v4
      with:
        version: 8
        run_install: false

    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'pnpm'

    - name: Install Dependencies
      run: pnpm install

    - name: Build
      run: pnpm build

    - name: Archive Build
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: |
          dist

    - name: Deploy (Clean)
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: $HOME/clean-addons.sh
        host: ${{ secrets.HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        privateKey: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy (Copy)
      uses: srueda99/scp-action@v12
      with:
        origin: dist
        destination: addons
        host: ${{ secrets.HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy (Execute)
      uses: garygrossgarten/github-action-ssh@release
      with:
        command:  $HOME/update-addons.sh
        host: ${{ secrets.HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
